name: "radio-conf-aarch64"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
          mkdir -p ~/.config/nix
          sudo bash -c "echo system-features = aarch64-linux arm-linux >> /etc/nix/nix.conf"
      - uses: cachix/cachix-action@v10
        with:
          name: dump-dvb
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --option system aarch64-linux --option sandbox false  --extra-platforms aarch64-linux -vL .\#packages.aarch64-linux.gnuradio-decoder
